### ISSUE TITLE
'ymcpssdk.h' file not found

### ISSUE THREAD

**Issue by hryamzik** [yandex-money/yandex-money-sdk-ios#3]
Just cloned the example project, installed pods and got the following errors:

`CustomUI/Pods/YandexMoneySDKiOS/Classes/YMABaseMoneySourcesView.h:10:9: 'ymcpssdk.h' file not found`
`CustomUI/Pods/YandexMoneySDKiOS/Classes/YMASecureStorage.h:7:9: 'ymcpssdk.h' file not found`

As I can see from the code this file should contain declaration of YMAMoneySource.

**Comment by Exwell** [comment]
Hello!

Sorry, but this project doesn't support. 
Please, see https://github.com/yandex-money/yandex-money-sdk-objc
